# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dd_integrate_bw_odeint <- function(ry, times, pars, atol, rtol, stepper) {
    .Call('_DDD_dd_integrate_bw_odeint', PACKAGE = 'DDD', ry, times, pars, atol, rtol, stepper)
}

#' @useDynLib DDD
NULL

dd_integrate_odeint <- function(ry, times, pars, atol, rtol, stepper) {
    .Call('_DDD_dd_integrate_odeint', PACKAGE = 'DDD', ry, times, pars, atol, rtol, stepper)
}

dd_integrate_td_odeint <- function(y, times, pars, atol, rtol, stepper) {
    .Call('_DDD_dd_integrate_td_odeint', PACKAGE = 'DDD', y, times, pars, atol, rtol, stepper)
}

dd_logliknorm1_odeint <- function(ry, times, pars, atol, rtol, stepper) {
    .Call('_DDD_dd_logliknorm1_odeint', PACKAGE = 'DDD', ry, times, pars, atol, rtol, stepper)
}

dd_logliknorm2_odeint <- function(ry, times, pars, atol, rtol, stepper) {
    .Call('_DDD_dd_logliknorm2_odeint', PACKAGE = 'DDD', ry, times, pars, atol, rtol, stepper)
}

